### ISSUE TITLE
Installation Error DNN v9.6

### ISSUE THREAD

**Issue by FatalSam** [openstore-ecommerce/OpenStore#103]
I am trying to install the module and I get the error > Failure A dependent package is not installed - NBrightTemplateSys
I have tried unzipping the contents under NBrightBuy_Resource and zip the install again no luck, any assistance will be appreciated.

StartJob Reading Installation Manifest file
Info Reading Package Manifest - Module - OS_ProductView
Failure A dependent package is not installed - NBrightTemplateSys
Info Reading Package Manifest - Skin - OpenStoreBO
Info Reading Component Manifest - Skin
Info Found valid path () for OpenStoreBO.ascx.
Info Found valid path () for OpenStoreBO.doctype.xml.

Thanks
Sam

**Comment by leedavi** [comment]
Hi,

There is a link to it on this page.

https://doc.openstore-ecommerce.com/

Keeping the template system separate is a legacy issue.  We plan to merge to 2 into 1 installation package in future.

**Comment by leedavi** [comment]
Oh also, we have had some reports of the JQuery having compatbility issues with OpenStore.  PLease report the issue here if you find the same.  

The next version of DNN should have an updated version of jQuery, which should solve the problem.  But we are looking for a solution for OpenStore before that.

**Comment by leedavi** [comment]
Also, sorry I forget to mention, I'll look at the path

**Comment by FatalSam** [comment]
> Hi,
> There is a link to it on this page.
> https://doc.openstore-ecommerce.com/
> Keeping the template system separate is a legacy issue.  We plan to merge to 2 into 1 installation package in future.

Thank you for your reply, I will try and follow the link above.

**Comment by leedavi** [comment]
I don;t see a problem with the Skin path...

        <component type="Skin">
          <skinFiles>
            <skinName>OpenStoreBO</skinName>
            <basePath>Portals\_default\Skins\OpenStoreBO</basePath>
            <skinFile>
              <name>OpenStoreBO.ascx</name>
            </skinFile>
            <skinFile>
              <name>OpenStoreBO.doctype.xml</name>
            </skinFile>
          </skinFiles>
        </component>


Can you explain more please?

**Comment by FatalSam** [comment]
Hi Lee,

I have managed to install successfully following > https://doc.openstore-ecommerce.com
I am not sure if I have missed something, I dont see the any NB setup/store configuration modules.
I can share the the temp site url with the admin login details.

Thanks in advance
Sam

**Comment by leedavi** [comment]
The setup is in the admin Panerl, which is installed with a skin.

https://doc.openstore-ecommerce.com/#11470

**Comment by FatalSam** [comment]
> The setup is in the admin Panerl, which is installed with a skin.
> https://doc.openstore-ecommerce.com/#11470

Hi Lee,

We are still not winning with the configuration back office, the skin is installed, reinstalled multiple times. Can I DM you the login details  maybe you can see something that we are not doing right.

Regards
Sam

**Comment by leedavi** [comment]
HI Sam,

Yes, sure.  I know on DNN9.6.0, there is some clashes with some modules for jQuery.  DNN9.6.1 is suppose to fix that.  I've not seen those errors on OpenStore, but you could try a DNN upgrade to v9.6.1

Regards,
Dave.

**Comment by leedavi** [comment]
Oh... 1 other thing.  OpenStore does not support Child (or sub) portals.  They were very much redundant years ago, but make sure it's a a normal portal you are using.    In fact it's so long since I looked at child portals I can't even remember if they are in DNN9

**Comment by FatalSam** [comment]
> Oh... 1 other thing.  OpenStore does not support Child (or sub) portals.  They were very much redundant years ago, but make sure it's a a normal portal you are using.    In fact it's so long since I looked at child portals I can't even remember if they are in DNN9

It's only portal.

> Oh... 1 other thing.  OpenStore does not support Child (or sub) portals.  They were very much redundant years ago, but make sure it's a a normal portal you are using.    In fact it's so long since I looked at child portals I can't even remember if they are in DNN9



> HI Sam,
> Yes, sure.  I know on DNN9.6.0, there is some clashes with some modules for jQuery.  DNN9.6.1 is suppose to fix that.  I've not seen those errors on OpenStore, but you could try a DNN upgrade to v9.6.1
> Regards,
> Dave.

Should I try to downgrade and install dnn 8? I think maybe dnn V9 persona bar > Admin could be the issue, as it's completely different from DNN 8 & DNN9.

**Comment by leedavi** [comment]
No need to downgrade that I know of.  But an upgrade to DNN9.6.1 would be the first step I would make.

There was a problem with DNN9.3 and 9.4 with multiple languages not being correct, but that is solved in DNN9.6.

I hate the PB, it has some good points but overall it is not a good UX.  There is an alternative, but you will need to purchase  it.  https://www.scotiacode.com/products/shine

**Comment by FatalSam** [comment]
Hi David,

 

I did the upgrade to V9.6.1 still no luck with the configuration under admin or PB maybe there’s something I am missing, below are two installs with the test login details maybe you can see something different.

 

DNN Upgraded from V9.6 to V9.6.1 with Store installed, but stuck on the store configuration

http://41.185.48.146/hothogs

 

Brand New DNN Install V9.6.1 No Store yet 

http://41.185.48.146/hothogs1 

 

login detail for both

madrush

#T3st@321

 

Thank You 

Sam

**Comment by leedavi** [comment]
Hi,

Those look very much like sub-portals??  OpenStore doesn't support subportals.  You need a valid portal url the store.

41.185.48.146/hothogs1

41.185.48.146/hothogs1

are 2 subportals of "41.185.48.146"

Create a url and link a portal to that so you have "www.hotdog.com" and "www.hotdog1.com"

I'll close this, reopen if you have a portal URL and still have the problem.

**Comment by FatalSam** [comment]
Hi David,

 

Duly noted.

 

Thank You

Sam
